FROM datacovesprivate/airflow-airflow:0.5.0

# pip install pandas==xx on /opt/datacoves/virtualenvs/main virtualenv
RUN /opt/datacoves/virtualenvs/main/bin/pip install pandas

RUN echo $DOCKERHUB_USER