# Detect changes on /schedule/images/*
# when changed, docker build schedule/images/pandas, docker push datacoves/airflow-pandas..

name: Test and Check on Pull Request

on:
  push:
    branches:
      - main
    paths:
      - "schedule/images/test/*"

env:
  HUB_USER: bantonellini
  HUB_PASS: Convexa*123

jobs:
  build:
    runs-on: ubuntu-latest
    name: Image build and push

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: bantonellini
          password: Convexa*123

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: schedule/images/test
          push: true
          tags: bantonellini/balboa-test:latest
