# Detect changes on /schedule/images/*
# when changed, docker build schedule/images/pandas, docker push datacoves/airflow-pandas..

name: Test and Check on Pull Request

on:
  push:
    branches:
      - main
    paths:
      - "schedule/images/test/*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Image build and push

    env:
      HUB_USER: bantonellini
      HUB_PASS: Convexa*123

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{HUB_USER}}
          password: ${{HUB_PASS}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: schedule/images/test
          push: true
          tags: ${{HUB_USER}}/balboa-test:latest
