# Detect changes on /schedule/images/*
# when changed, docker build schedule/images/pandas, docker push datacoves/airflow-pandas..

name: Test and Check on Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Image build and push

    env:
      DOCKERHUB_USER: antonellinibruno@gmail.com
      DOCKERHUB_PASS: Lola*5014

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Get changed images
        id: changed-images
        uses: tj-actions/changed-files@v23

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{DOCKERHUB_USER}}
          password: ${{DOCKERHUB_PASS}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
